# ============================================================================
# WOF MANAGED FILE - DO NOT EDIT MANUALLY
# This file is managed by the Workload Orchestration Framework.
# Changes will be overwritten on the next WOF sync/update.
# To customize behavior, use configuration files in .ai/config/
# ============================================================================

# Learned Rules Manager
#
# Manages user-approved behavioral rules detected from prompt patterns.
# Handles CRUD operations on .ai/state/learned-rules.json and injects
# active rules into CLAUDE.md between marker comments.
#
# Usage:
#   & '.\manage-learned-rules.ps1' -Action list
#   & '.\manage-learned-rules.ps1' -Action add -Category "testing" -EnforcementText "Run full test suite before committing" -Confidence 0.85
#   & '.\manage-learned-rules.ps1' -Action remove -RuleId "rule-001"
#   & '.\manage-learned-rules.ps1' -Action clear
#   & '.\manage-learned-rules.ps1' -Action apply

param(
    [Parameter(Mandatory=$true)]
    [ValidateSet('list', 'add', 'remove', 'clear', 'apply')]
    [string]$Action,

    [Parameter(Mandatory=$false)]
    [string]$RuleId = "",

    [Parameter(Mandatory=$false)]
    [string]$Category = "",

    [Parameter(Mandatory=$false)]
    [string]$EnforcementText = "",

    [Parameter(Mandatory=$false)]
    [double]$Confidence = 0.0,

    [Parameter(Mandatory=$false)]
    [switch]$JsonOutput
)

# Resolve paths
$repoPath = if ($env:CLAUDE_PROJECT_DIR) { $env:CLAUDE_PROJECT_DIR } else { (Get-Item $PSScriptRoot).Parent.Parent.FullName }
$stateDir = Join-Path $repoPath ".ai\state"
$rulesFile = Join-Path $stateDir "learned-rules.json"
$claudeMd = Join-Path $repoPath "CLAUDE.md"

# Markers for CLAUDE.md injection
$markerStart = "<!-- LEARNED-PATTERNS-START - Auto-generated by /wof patterns. Managed by WOF. -->"
$markerEnd = "<!-- LEARNED-PATTERNS-END -->"
$woiEnd = "<!-- WOI-SECTION-END -->"

# Ensure state directory exists
if (-not (Test-Path $stateDir)) {
    New-Item -ItemType Directory -Force -Path $stateDir | Out-Null
}

# Load or create rules file
function Get-RulesData {
    if (Test-Path $rulesFile) {
        return Get-Content $rulesFile -Raw | ConvertFrom-Json
    }
    return [PSCustomObject]@{
        version       = "1.0.0"
        last_analysis = $null
        rules         = @()
    }
}

function Save-RulesData($data) {
    $data | ConvertTo-Json -Depth 5 | Set-Content -Path $rulesFile -Encoding UTF8
}

function Get-NextRuleId($rules) {
    if ($rules.Count -eq 0) { return "rule-001" }
    $maxNum = 0
    foreach ($r in $rules) {
        if ($r.id -match 'rule-(\d+)') {
            $num = [int]$Matches[1]
            if ($num -gt $maxNum) { $maxNum = $num }
        }
    }
    return "rule-{0:D3}" -f ($maxNum + 1)
}

# --- Actions ---

switch ($Action) {
    'list' {
        $data = Get-RulesData
        $rules = @($data.rules)
        if ($JsonOutput) {
            return $data | ConvertTo-Json -Depth 5
        }
        if ($rules.Count -eq 0) {
            Write-Output "No learned rules."
            return @{ RuleCount = 0 }
        }
        Write-Output "Learned Rules ($($rules.Count)):"
        Write-Output ""
        foreach ($r in $rules) {
            $status = if ($r.active) { "ACTIVE" } else { "INACTIVE" }
            Write-Output "  [$($r.id)] [$status] [$($r.category)] (confidence: $($r.confidence))"
            Write-Output "    $($r.enforcement_text)"
            Write-Output ""
        }
        return @{ RuleCount = $rules.Count; Rules = $rules }
    }

    'add' {
        if (-not $Category) { throw "Category is required for add action" }
        if (-not $EnforcementText) { throw "EnforcementText is required for add action" }

        $data = Get-RulesData
        $rules = @($data.rules)
        $newId = Get-NextRuleId $rules

        $newRule = [PSCustomObject]@{
            id               = $newId
            category         = $Category
            enforcement_text = $EnforcementText
            confidence       = $Confidence
            added_at         = (Get-Date -Format "yyyy-MM-ddTHH:mm:ss.fffZ")
            active           = $true
        }

        $rules += $newRule
        $data.rules = $rules
        Save-RulesData $data

        Write-Output "Added rule $newId : $EnforcementText"
        return @{ Added = $true; RuleId = $newId }
    }

    'remove' {
        if (-not $RuleId) { throw "RuleId is required for remove action" }

        $data = Get-RulesData
        $rules = @($data.rules)
        $found = $false

        $newRules = @()
        foreach ($r in $rules) {
            if ($r.id -eq $RuleId) {
                $found = $true
            } else {
                $newRules += $r
            }
        }

        if (-not $found) {
            Write-Output "Rule $RuleId not found."
            return @{ Removed = $false; Reason = "Not found" }
        }

        $data.rules = $newRules
        Save-RulesData $data

        Write-Output "Removed rule $RuleId."
        return @{ Removed = $true; RuleId = $RuleId }
    }

    'clear' {
        $data = Get-RulesData
        $data.rules = @()
        $data.last_analysis = $null
        Save-RulesData $data

        Write-Output "All learned rules cleared."
        return @{ Cleared = $true }
    }

    'apply' {
        $data = Get-RulesData
        $activeRules = @($data.rules | Where-Object { $_.active -eq $true })

        if (-not (Test-Path $claudeMd)) {
            Write-Output "CLAUDE.md not found at $claudeMd"
            return @{ Applied = $false; Reason = "CLAUDE.md not found" }
        }

        $content = Get-Content $claudeMd -Raw

        # Build the new section (or empty if no active rules)
        $newSection = ""
        if ($activeRules.Count -gt 0) {
            $lines = @()
            $lines += $markerStart
            $lines += "### Learned User Preferences"
            $lines += ""
            $lines += "These rules were detected from recurring patterns in your instructions and approved by you."
            $lines += "Re-run ``/wof patterns`` to review or modify."
            $lines += ""
            $i = 1
            foreach ($r in $activeRules) {
                $lines += "$i. **$($r.category)**: $($r.enforcement_text)"
                $i++
            }
            $lines += $markerEnd
            $newSection = ($lines -join "`n")
        }

        # Check if markers already exist
        $hasMarkers = $content.Contains("<!-- LEARNED-PATTERNS-START")

        if ($hasMarkers) {
            # Replace between markers (inclusive)
            $pattern = "(?s)<!-- LEARNED-PATTERNS-START[^>]*-->.*?<!-- LEARNED-PATTERNS-END -->"
            if ($newSection) {
                $content = [regex]::Replace($content, $pattern, $newSection)
            } else {
                # Remove the section entirely (plus surrounding blank lines)
                $content = [regex]::Replace($content, "(?s)\r?\n?\r?\n?<!-- LEARNED-PATTERNS-START[^>]*-->.*?<!-- LEARNED-PATTERNS-END -->\r?\n?", "")
            }
        } elseif ($newSection) {
            # Insert after WOI-SECTION-END
            if ($content.Contains($woiEnd)) {
                $content = $content.Replace($woiEnd, "$woiEnd`n`n$newSection")
            } else {
                # Fallback: append to end
                $content = $content.TrimEnd() + "`n`n$newSection`n"
            }
        }
        # If no markers and no new section, nothing to do

        Set-Content -Path $claudeMd -Value $content -NoNewline -Encoding UTF8

        $msg = if ($activeRules.Count -gt 0) { "Applied $($activeRules.Count) rule(s) to CLAUDE.md" } else { "Removed learned patterns section from CLAUDE.md" }
        Write-Output $msg
        return @{ Applied = $true; ActiveRules = $activeRules.Count }
    }
}
